update spring boot
boomerang-io/bosun.service.repository pull request #5
Opened 2022-05-05 14:00 UTC by amhudson

Closes #
https://github.com/boomerang-io/roadmap/issues/339

#### Changelog

**New**

- N/A

**Changed**

- Update Spring Boot to 2.6.6

**Removed**

- N/A

#### Testing / Reviewing

Tested and verified locally

2022-05-05 15:05 UTC, AndreiOla requested changes

2022-05-05 15:05 UTC, AndreiOla commented on pom.xml
>  		<spring.data>2.1.9.RELEASE</spring.data>
This lib needs to be correlated also with spring-boot 2.6.6: spring-data-commons | 2.6.3

2022-05-05 15:05 UTC, AndreiOla commented on pom.xml
>  			<version>1.0.0</version>
I think this needs to be updated to  1.2.4. Not sure where is the repo for these libraries.

2022-05-05 15:05 UTC, AndreiOla commented on pom.xml
>  			<version>1.0.1</version>
This library seems to be renamed 4 years ago and the last tag is 0.0.7, so I'm not sure where that 1.0.1 version is taken from. Might be a public repository?

2022-05-05 16:12 UTC, amhudson commented on pom.xml
>  			<version>1.0.1</version>
`lib-rest` is now called `lib-proxy`. updated with latest

2022-05-06 06:45 UTC, AndreiOla approved these changes

2022-05-06 14:51 UTC, amhudson commented
@tlawrie Did you want to review?

2022-05-10 14:22 UTC, morarucostel approved these changes

2022-05-10 14:22 UTC, merged